### PR TITLE
Resolving #53

### PR DESCRIPTION
**Pull request by Polyneue**
Adds in a step before logging a successful build that parses the README.md file and updates with given app name.

Let me know if this is what you were looking for!

### CODE REVIEW

**Comment by italopessoa** [comment]
Looks great @Polyneue. 💃

**Comment by jouderianjr** [comment]
Hey @Polyneue sorry for the late response. 

I'm getting this error:

`env: node\r: No such file or directory`

are you using windows? windows by default breaks the line using \r\n, but the unix like system only uses \n.

You can use editorconfig in order to fix that 😄

**Comment by Polyneue** [comment]
@jouderianjr - I'm not on windows, running OSX with Node 8.1.3. Which version are you using to test the update?

Edit: I also saw that error when I first started working on the update, but it was related to not specifying a directory to write to. For example: `awesome-react-app` instead of `awesome-react-app my-new-dir`

**Review by jouderianjr — APPROVED** [review]
Yeah, I just tried on a different computer and worked. I'll try to understand what happened.

Anyway, nice work! Thank you for your help 💃

**Pull request merged**
