### PR TITLE
First proposal for the CLI

### PR DESCRIPTION
**Pull request by jouderianjr**
Hey everyone. this PR basically has a proposal for create an extensible cli. The main feature of this project are the `hooks`.

Using `hooks` we are able to add infinite hooks and add more and more features for this project.

One hook should return an object with 2 fields: question and action. Please take a look on `hooks/editorconfig/index.js` for understand how this works.

💃

### CODE REVIEW

**Comment by jourdanrodrigues** [comment]
@jouderianjr Really liked the approach! I'd like to add some thoughts/proposals before my review:

I think we should trigger own ESLint CLI installation and wait for it to finish before going to the next steps (but it could easily become a choice). We could do it for all CLI based configurations.

In addition to this idea, I'm don't remember seeing a CLI for creating a custom `.editorconfig`, asking the style wanted (just like ESLint CLI). We could work on it as well.

Let me know your thoughts.

**Review by jvcjunior — APPROVED** [review]
Awesome!!!

**Review by italopessoa — CHANGES_REQUESTED** [review]
I tried to execute the command on my machine and get this.
'awesome-react-app' is not recognized as an internal or external command,
operable program or batch file.

It only recognizes `awesome-react-app.cmd`. Also, I get a yarn error while creating the project, seems like a network error.

UPDATE: when restart the cmd, the command was recognized, but yarn package error still the same.
> Creating a new React app in C:\ara\teste.                                                                                                                    
>                                                                                                                                                              
> Installing packages. This might take a couple of minutes.                                                                                                    
> Installing react, react-dom, and react-scripts...                                                                                                            
>                                                                                                                                                              
> yarn add v1.0.1                                                                                                                                              
> info No lockfile found.                                                                                                                                      
> [1/4] Resolving packages...                                                                                                                                  
> error An unexpected error occurred: "https://registry.yarnpkg.com/isomorphic-fetch: connect ETIMEDOUT 104.16.62.173:443".                                    
> info If you think this is a bug, please open a bug report with the information provided in "C:\\ara\\teste\\yarn-error.log".                                 
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.                                                                         
> Error: connect ETIMEDOUT 104.16.62.173:443                                                                                                                   
>     at Object.exports._errnoException (util.js:1020:11)                                                                                                      
>     at exports._exceptionWithHostPort (util.js:1043:20)                                                                                                      
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)                                                                                          
>                                                                                                                                                              
> Aborting installation.                                                                                                                                       
>   yarnpkg add --exact react react-dom react-scripts has failed.                                                                                              
>                                                                                                                                                              
> Deleting generated file... package.json                                                                                                                      
> Deleting generated file... yarn-error.log                                                                                                                    
> Deleting teste / from C:\ara                                                                                                                                 
> Done.                                                                                                                                                        
> (node:13548) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ChildProcessError: `create-react-app teste` failed with code 1 Creating a new React app in C:\ara\teste.                                                                                                                    
>                                                                                                                                                              
> Installing packages. This might take a couple of minutes.                                                                                                    
> Installing react, react-dom, and react-scripts...                                                                                                            
>                                                                                                                                                              
> yarn add v1.0.1                                                                                                                                              
> info No lockfile found.                                                                                                                                      
> [1/4] Resolving packages...                                                                                                                                  
> error An unexpected error occurred: "https://registry.yarnpkg.com/isomorphic-fetch: connect ETIMEDOUT 104.16.62.173:443".                                    
> info If you think this is a bug, please open a bug report with the information provided in "C:\\ara\\teste\\yarn-error.log".                                 
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.                                                                         
> Error: connect ETIMEDOUT 104.16.62.173:443                                                                                                                   
>     at Object.exports._errnoException (util.js:1020:11)                                                                                                      
>     at exports._exceptionWithHostPort (util.js:1043:20)                                                                                                      
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)                                                                                          
>                                                                                                                                                              
> Aborting installation.                                                                                                                                       
>   yarnpkg add --exact react react-dom react-scripts has failed.                                                                                              
>                                                                                                                                                              
> Deleting generated file... package.json                                                                                                                      
> Deleting generated file... yarn-error.log                                                                                                                    
> Deleting teste / from C:\ara                                                                                                                                 
> Done.                                                                                                                                                        
> (node:13548) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ChildProcessError: `create-react-app teste` failed with code 1

**Comment by jvcjunior** [comment]
@italopessoa this is happening because of your node version. There's a problem on windows indeed but we are going to create a new issue to work on that.

**Comment by italopessoa** [comment]
I see @jvcjunior.  So keep going guys.

**Review by italopessoa — APPROVED** [review]

**Pull request merged**
