### PR TITLE
[feature] Add Redux Hook

### PR DESCRIPTION
**Pull request by rbrodbeck15**
# Issue
[Add Redux Hook](https://github.com/ifactory-solutions/awesome-react-app/issues/48)

# Follow-up Question
- Should there be an initial store example when adding this hook? If so, is that required for this PR or make another issue for that?

### CODE REVIEW

**Comment by italopessoa** [comment]
Hi, @rbrodbeck15 thanks for contribute. I think that it would be very useful a simple example, and it's ok for me to put in on the current PR.

**Comment by jouderianjr** [comment]
Yeah, I agree with @italopessoa, would be better have a <Provider>, a file with the store and a file with a reducer example 😄

**Review by jouderianjr — APPROVED** [review]
Hey, awesome! Thanks for that mate 💃

**Comment by jouderianjr** [comment]
@italopessoa Could you test it on windows env? If it works properly, I will merge it.

**Comment by italopessoa** [comment]
Works like a charm @jouderianjr

**Pull request merged**
